SELECT * FROM products ORDER BY id LIMIT 5;

SELECT * FROM products ORDER BY id LIMIT 3;

SELECT * FROM products ORDER BY id LIMIT 0, 5;

SELECT * FROM products ORDER BY id LIMIT 5, 5;

SELECT * FROM products ORDER BY id LIMIT 10, 5;

SELECT * FROM products ORDER BY id LIMIT 15, 5;